basePath: /
host: localhost:8080
info:
  contact: {}
  description: API for managing books and processing URLs
  title: TaskGo API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns 200 OK if the service is up
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
