name: Go Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true

      - name: Install Go dependencies
        run: go mod tidy

      - name: Run go vet
        run: go vet ./...

      - name: Run tests
        run: go test ./... -cover

      - name: Check Swagger docs
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init --parseDependency --parseInternal
          git diff --exit-code docs/ || { echo 'Swagger docs out of sync. Run swag init locally.'; exit 1; }

      - name: Docker build (validation only)
        run: docker build -t taskgo-backend ./Backend
